name: Pipeline CI DevOps Project 2

on:
  pull_request:
  push:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Specify the start time
        run: echo "Start time $(date)"
        


      - name: Install dependencies
        run: npm install

      - name: Check-out files from repository
        uses: actions/checkout@v2

      - name: Prettier
        run: npx prettier --write .

      - name: Eslint
        run: npx eslint --fix .

      - name: Jest test
        run: npx jest --coverage

      - name: Build project
        run: npm run build
        
      - name: Pipeline status
        if: success()
        run: echo "PIPELINE SUCCESS WITHOUT ERRORS"

      - name: Specify the end time
        run: echo "End time $(date)"
